/**
 * Категория «Файлы и медиа» (Этап 4, часть F).
 *
 * Операции с файлами, изображениями, аудио и видео. Определения
 * фиксируют контракты (статус `planned`, скрыты из палитры): работа
 * с файловым хранилищем появится вместе с серверной частью
 * (см. docs/DATABASE.md).
 */

import type { BlockDefinition } from '@/core/types/blocks';
import { dport, eport } from '../shared';

const mediaColor = '#f472b6';

export const mediaBlocks: BlockDefinition[] = [
  {
    id: 'media.image_upload',
    version: '1',
    labelKey: 'blocks.media.image_upload.label',
    descriptionKey: 'blocks.media.image_upload.description',
    keywords: ['файл', 'картинка', 'загрузить', 'изображение', 'выбор'],
    category: 'media',
    subcategory: 'изображения',
    difficulty: 'basic',
    status: 'planned',
    available: false,
    inputs: [dport('file', 'blocks.ports.file', 'file')],
    outputs: [dport('image', 'blocks.ports.image', 'image'), eport()],
    ui: { icon: '🖼️', color: mediaColor },
  },
  {
    id: 'media.image_resize',
    version: '1',
    labelKey: 'blocks.media.image_resize.label',
    descriptionKey: 'blocks.media.image_resize.description',
    keywords: ['файл', 'картинка', 'размер', 'масштаб', 'обрезать'],
    category: 'media',
    subcategory: 'изображения',
    difficulty: 'advanced',
    status: 'planned',
    available: false,
    inputs: [
      dport('image', 'blocks.ports.image', 'image'),
      dport('width', 'blocks.ports.width', 'number'),
      dport('height', 'blocks.ports.height', 'number'),
    ],
    outputs: [dport('image', 'blocks.ports.image', 'image'), eport()],
    ui: { icon: '📐', color: mediaColor },
  },
  {
    id: 'media.image_info',
    version: '1',
    labelKey: 'blocks.media.image_info.label',
    descriptionKey: 'blocks.media.image_info.description',
    keywords: ['файл', 'картинка', 'свойства', 'ширина', 'высота'],
    category: 'media',
    subcategory: 'изображения',
    difficulty: 'basic',
    status: 'planned',
    available: false,
    inputs: [dport('image', 'blocks.ports.image', 'image')],
    outputs: [dport('info', 'blocks.ports.info', 'object'), eport()],
    ui: { icon: '🔍', color: mediaColor },
  },
  {
    id: 'media.file_info',
    version: '1',
    labelKey: 'blocks.media.file_info.label',
    descriptionKey: 'blocks.media.file_info.description',
    keywords: ['файл', 'свойства', 'имя', 'размер', 'тип'],
    category: 'media',
    subcategory: 'файлы',
    difficulty: 'basic',
    status: 'planned',
    available: false,
    inputs: [dport('file', 'blocks.ports.file', 'file')],
    outputs: [dport('info', 'blocks.ports.info', 'object'), eport()],
    ui: { icon: 'ℹ️', color: mediaColor },
  },
  {
    id: 'media.file_read_text',
    version: '1',
    labelKey: 'blocks.media.file_read_text.label',
    descriptionKey: 'blocks.media.file_read_text.description',
    keywords: ['файл', 'прочитать', 'текст', 'содержимое'],
    category: 'media',
    subcategory: 'файлы',
    difficulty: 'basic',
    status: 'planned',
    available: false,
    inputs: [dport('file', 'blocks.ports.file', 'file')],
    outputs: [dport('text', 'blocks.ports.text', 'text'), eport()],
    ui: { icon: '📖', color: mediaColor },
  },
  {
    id: 'media.file_to_base64',
    version: '1',
    labelKey: 'blocks.media.file_to_base64.label',
    descriptionKey: 'blocks.media.file_to_base64.description',
    keywords: ['файл', 'база64', 'кодировать', 'строка'],
    category: 'media',
    subcategory: 'файлы',
    difficulty: 'advanced',
    status: 'planned',
    available: false,
    inputs: [dport('file', 'blocks.ports.file', 'file')],
    outputs: [dport('text', 'blocks.ports.text', 'text'), eport()],
    ui: { icon: '🧬', color: mediaColor },
  },
  {
    id: 'media.base64_to_file',
    version: '1',
    labelKey: 'blocks.media.base64_to_file.label',
    descriptionKey: 'blocks.media.base64_to_file.description',
    keywords: ['файл', 'база64', 'раскодировать', 'восстановить'],
    category: 'media',
    subcategory: 'файлы',
    difficulty: 'advanced',
    status: 'planned',
    available: false,
    inputs: [dport('text', 'blocks.ports.text', 'text')],
    outputs: [dport('file', 'blocks.ports.file', 'file'), eport()],
    ui: { icon: '📦', color: mediaColor },
  },
  {
    id: 'media.audio_info',
    version: '1',
    labelKey: 'blocks.media.audio_info.label',
    descriptionKey: 'blocks.media.audio_info.description',
    keywords: ['файл', 'аудио', 'звук', 'музыка', 'длительность'],
    category: 'media',
    subcategory: 'аудио и видео',
    difficulty: 'advanced',
    status: 'planned',
    available: false,
    inputs: [dport('file', 'blocks.ports.file', 'file')],
    outputs: [dport('info', 'blocks.ports.info', 'object'), eport()],
    ui: { icon: '🎵', color: mediaColor },
  },
  {
    id: 'media.video_info',
    version: '1',
    labelKey: 'blocks.media.video_info.label',
    descriptionKey: 'blocks.media.video_info.description',
    keywords: ['файл', 'видео', 'ролик', 'длительность', 'разрешение'],
    category: 'media',
    subcategory: 'аудио и видео',
    difficulty: 'advanced',
    status: 'planned',
    available: false,
    inputs: [dport('file', 'blocks.ports.file', 'file')],
    outputs: [dport('info', 'blocks.ports.info', 'object'), eport()],
    ui: { icon: '🎬', color: mediaColor },
  },
  {
    id: 'media.url_download',
    version: '1',
    labelKey: 'blocks.media.url_download.label',
    descriptionKey: 'blocks.media.url_download.description',
    keywords: ['файл', 'скачать', 'адрес', 'интернет', 'сохранить'],
    category: 'media',
    subcategory: 'файлы',
    difficulty: 'basic',
    status: 'planned',
    available: false,
    inputs: [dport('url', 'blocks.ports.url', 'url')],
    outputs: [dport('file', 'blocks.ports.file', 'file'), eport()],
    ui: { icon: '⬇️', color: mediaColor },
  },
];
