/**
 * Категория «Память» (Этап 4, часть D).
 *
 * Операции с памятью выполнения (переменные проекта и списка значений).
 * Определения фиксируют контракты (статус `planned`, скрыты из палитры):
 * исполняемое хранилище появится вместе с развитием переменных проекта
 * (см. docs/MASTER_SPEC.md §«Выполнение»). Зарезервированные
 * `memory.variable` / `memory.shared` живут в reserved.ts и остаются
 * архитектурными заготовками.
 */

import type { BlockDefinition } from '@/core/types/blocks';
import { dport, eport } from '../shared';

const memColor = '#a78bfa';

export const memoryBlocks: BlockDefinition[] = [
  {
    id: 'memory.get',
    version: '1',
    labelKey: 'blocks.memory.get.label',
    descriptionKey: 'blocks.memory.get.description',
    keywords: ['память', 'переменная', 'чтение', 'значение', 'получить'],
    category: 'memory',
    subcategory: 'переменные',
    difficulty: 'basic',
    status: 'planned',
    available: false,
    inputs: [],
    outputs: [dport('value', 'blocks.ports.value', 'any')],
    defaults: { key: '' },
    ui: { icon: '📖', color: memColor },
  },
  {
    id: 'memory.set',
    version: '1',
    labelKey: 'blocks.memory.set.label',
    descriptionKey: 'blocks.memory.set.description',
    keywords: ['память', 'переменная', 'запись', 'значение', 'установить'],
    category: 'memory',
    subcategory: 'переменные',
    difficulty: 'basic',
    status: 'planned',
    available: false,
    inputs: [dport('value', 'blocks.ports.value', 'any')],
    outputs: [dport('value', 'blocks.ports.value', 'any')],
    defaults: { key: '' },
    ui: { icon: '✍️', color: memColor },
  },
  {
    id: 'memory.increment',
    version: '1',
    labelKey: 'blocks.memory.increment.label',
    descriptionKey: 'blocks.memory.increment.description',
    keywords: ['память', 'счётчик', 'плюс', 'увеличить', 'число'],
    category: 'memory',
    subcategory: 'счётчики',
    difficulty: 'basic',
    status: 'planned',
    available: false,
    inputs: [dport('step', 'blocks.ports.step', 'number')],
    outputs: [dport('value', 'blocks.ports.value', 'number')],
    defaults: { key: '', step: 1 },
    ui: { icon: '➕', color: memColor },
  },
  {
    id: 'memory.decrement',
    version: '1',
    labelKey: 'blocks.memory.decrement.label',
    descriptionKey: 'blocks.memory.decrement.description',
    keywords: ['память', 'счётчик', 'минус', 'уменьшить', 'число'],
    category: 'memory',
    subcategory: 'счётчики',
    difficulty: 'basic',
    status: 'planned',
    available: false,
    inputs: [dport('step', 'blocks.ports.step', 'number')],
    outputs: [dport('value', 'blocks.ports.value', 'number')],
    defaults: { key: '', step: 1 },
    ui: { icon: '➖', color: memColor },
  },
  {
    id: 'memory.list_append',
    version: '1',
    labelKey: 'blocks.memory.list_append.label',
    descriptionKey: 'blocks.memory.list_append.description',
    keywords: ['память', 'список', 'добавить', 'журнал', 'накопить'],
    category: 'memory',
    subcategory: 'списки',
    difficulty: 'advanced',
    status: 'planned',
    available: false,
    inputs: [dport('item', 'blocks.ports.item', 'any')],
    outputs: [dport('length', 'blocks.ports.length', 'number')],
    defaults: { key: '' },
    ui: { icon: '📥', color: memColor },
  },
  {
    id: 'memory.list_length',
    version: '1',
    labelKey: 'blocks.memory.list_length.label',
    descriptionKey: 'blocks.memory.list_length.description',
    keywords: ['память', 'список', 'длина', 'количество', 'размер'],
    category: 'memory',
    subcategory: 'списки',
    difficulty: 'basic',
    status: 'planned',
    available: false,
    inputs: [],
    outputs: [dport('length', 'blocks.ports.length', 'number')],
    defaults: { key: '' },
    ui: { icon: '🧮', color: memColor },
  },
  {
    id: 'memory.exists',
    version: '1',
    labelKey: 'blocks.memory.exists.label',
    descriptionKey: 'blocks.memory.exists.description',
    keywords: ['память', 'переменная', 'существует', 'проверка', 'есть ли'],
    category: 'memory',
    subcategory: 'переменные',
    difficulty: 'advanced',
    status: 'planned',
    available: false,
    inputs: [],
    outputs: [dport('exists', 'blocks.ports.exists', 'boolean')],
    defaults: { key: '' },
    ui: { icon: '❓', color: memColor },
  },
  {
    id: 'memory.clear',
    version: '1',
    labelKey: 'blocks.memory.clear.label',
    descriptionKey: 'blocks.memory.clear.description',
    keywords: ['память', 'очистить', 'сброс', 'удалить', 'обнулить'],
    category: 'memory',
    subcategory: 'служебные',
    difficulty: 'advanced',
    status: 'planned',
    available: false,
    inputs: [],
    outputs: [dport('ok', 'blocks.ports.ok', 'boolean'), eport()],
    defaults: { key: '' },
    ui: { icon: '🧹', color: memColor },
  },
];
