/**
 * Базовый курс «NODEZZLE с нуля» (подэтап 5.11, часть D).
 *
 * Каждый интерактивный шаг опирается только на реально работающие
 * функции продукта (реестр блоков, рантайм, симулятор). Ссылки на
 * блоки проверяются валидатором каталога относительно живого реестра.
 */

import type { LessonDefinition } from '../types';

const K = (lesson: string) => `academy.lessons.${lesson}`;

export const baseCourse: readonly LessonDefinition[] = [
  // ---------- Уровень 1. Знакомство ----------
  {
    id: 'intro-what',
    level: 1,
    track: 'basics',
    titleKey: K('intro-what') + '.title',
    descriptionKey: K('intro-what') + '.description',
    estimatedMinutes: 4,
    difficulty: 'basic',
    prerequisites: [],
    sandbox: false,
    relatedBlockIds: ['core.text', 'debug.log'],
    steps: [
      {
        id: 'about',
        kind: 'information',
        titleKey: K('intro-what') + '.steps.about.title',
        textKey: K('intro-what') + '.steps.about.text',
        detailsKey: K('intro-what') + '.steps.about.details',
      },
      {
        id: 'how',
        kind: 'information',
        titleKey: K('intro-what') + '.steps.how.title',
        textKey: K('intro-what') + '.steps.how.text',
        detailsKey: K('intro-what') + '.steps.how.details',
      },
      {
        id: 'quiz-input',
        kind: 'quiz',
        titleKey: K('intro-what') + '.steps.quizInput.title',
        textKey: K('intro-what') + '.steps.quizInput.text',
        questionKey: K('intro-what') + '.steps.quizInput.question',
        options: [
          { id: 'input', labelKey: K('intro-what') + '.steps.quizInput.optInput', correct: true },
          { id: 'output', labelKey: K('intro-what') + '.steps.quizInput.optOutput', correct: false },
          { id: 'canvas', labelKey: K('intro-what') + '.steps.quizInput.optCanvas', correct: false },
        ],
      },
      {
        id: 'quiz-flow',
        kind: 'quiz',
        titleKey: K('intro-what') + '.steps.quizFlow.title',
        textKey: K('intro-what') + '.steps.quizFlow.text',
        questionKey: K('intro-what') + '.steps.quizFlow.question',
        options: [
          { id: 'wires', labelKey: K('intro-what') + '.steps.quizFlow.optWires', correct: false },
          { id: 'connections', labelKey: K('intro-what') + '.steps.quizFlow.optConnections', correct: true },
          { id: 'nothing', labelKey: K('intro-what') + '.steps.quizFlow.optNothing', correct: false },
        ],
      },
    ],
  },
  {
    id: 'intro-canvas',
    level: 1,
    track: 'basics',
    titleKey: K('intro-canvas') + '.title',
    descriptionKey: K('intro-canvas') + '.description',
    estimatedMinutes: 5,
    difficulty: 'basic',
    prerequisites: ['intro-what'],
    sandbox: true,
    relatedBlockIds: ['core.text'],
    steps: [
      {
        id: 'canvas',
        kind: 'information',
        titleKey: K('intro-canvas') + '.steps.canvas.title',
        textKey: K('intro-canvas') + '.steps.canvas.text',
        target: 'canvas',
      },
      {
        id: 'library',
        kind: 'information',
        titleKey: K('intro-canvas') + '.steps.library.title',
        textKey: K('intro-canvas') + '.steps.library.text',
        hintKey: K('intro-canvas') + '.steps.library.hint',
        target: 'library',
      },
      {
        id: 'add-text',
        kind: 'add-block',
        blockId: 'core.text',
        titleKey: K('intro-canvas') + '.steps.addText.title',
        textKey: K('intro-canvas') + '.steps.addText.text',
        hintKey: K('intro-canvas') + '.steps.addText.hint',
        target: 'library',
      },
      {
        id: 'select-text',
        kind: 'select-block',
        blockId: 'core.text',
        titleKey: K('intro-canvas') + '.steps.selectText.title',
        textKey: K('intro-canvas') + '.steps.selectText.text',
        hintKey: K('intro-canvas') + '.steps.selectText.hint',
        target: 'inspector',
      },
      {
        id: 'inspector',
        kind: 'information',
        titleKey: K('intro-canvas') + '.steps.inspector.title',
        textKey: K('intro-canvas') + '.steps.inspector.text',
        detailsKey: K('intro-canvas') + '.steps.inspector.details',
        target: 'inspector',
      },
    ],
  },

  // ---------- Уровень 2. Детали и соединения ----------
  {
    id: 'basics-ports',
    level: 2,
    track: 'basics',
    titleKey: K('basics-ports') + '.title',
    descriptionKey: K('basics-ports') + '.description',
    estimatedMinutes: 6,
    difficulty: 'basic',
    prerequisites: ['intro-canvas'],
    sandbox: true,
    relatedBlockIds: ['core.text', 'telegram.send_message'],
    steps: [
      {
        id: 'about-ports',
        kind: 'information',
        titleKey: K('basics-ports') + '.steps.aboutPorts.title',
        textKey: K('basics-ports') + '.steps.aboutPorts.text',
        detailsKey: K('basics-ports') + '.steps.aboutPorts.details',
      },
      {
        id: 'add-sender',
        kind: 'add-block',
        blockId: 'telegram.send_message',
        titleKey: K('basics-ports') + '.steps.addSender.title',
        textKey: K('basics-ports') + '.steps.addSender.text',
        hintKey: K('basics-ports') + '.steps.addSender.hint',
        target: 'library',
      },
      {
        id: 'add-value',
        kind: 'add-block',
        blockId: 'core.text',
        titleKey: K('basics-ports') + '.steps.addValue.title',
        textKey: K('basics-ports') + '.steps.addValue.text',
      },
      {
        id: 'shapes',
        kind: 'information',
        titleKey: K('basics-ports') + '.steps.shapes.title',
        textKey: K('basics-ports') + '.steps.shapes.text',
        detailsKey: K('basics-ports') + '.steps.shapes.details',
      },
      {
        id: 'quiz-error',
        kind: 'quiz',
        titleKey: K('basics-ports') + '.steps.quizError.title',
        textKey: K('basics-ports') + '.steps.quizError.text',
        questionKey: K('basics-ports') + '.steps.quizError.question',
        options: [
          { id: 'circle', labelKey: K('basics-ports') + '.steps.quizError.optCircle', correct: false },
          { id: 'square', labelKey: K('basics-ports') + '.steps.quizError.optSquare', correct: true },
          { id: 'diamond', labelKey: K('basics-ports') + '.steps.quizError.optDiamond', correct: false },
        ],
      },
    ],
  },
  {
    id: 'basics-chain',
    level: 2,
    track: 'basics',
    titleKey: K('basics-chain') + '.title',
    descriptionKey: K('basics-chain') + '.description',
    estimatedMinutes: 7,
    difficulty: 'basic',
    prerequisites: ['basics-ports'],
    sandbox: true,
    relatedBlockIds: ['telegram.message_received', 'debug.log'],
    steps: [
      {
        id: 'add-trigger',
        kind: 'add-block',
        blockId: 'telegram.message_received',
        titleKey: K('basics-chain') + '.steps.addTrigger.title',
        textKey: K('basics-chain') + '.steps.addTrigger.text',
        detailsKey: K('basics-chain') + '.steps.addTrigger.details',
        hintKey: K('basics-chain') + '.steps.addTrigger.hint',
        target: 'library',
      },
      {
        id: 'add-log',
        kind: 'add-block',
        blockId: 'debug.log',
        titleKey: K('basics-chain') + '.steps.addLog.title',
        textKey: K('basics-chain') + '.steps.addLog.text',
        hintKey: K('basics-chain') + '.steps.addLog.hint',
      },
      {
        id: 'connect',
        kind: 'connect',
        fromBlockId: 'telegram.message_received',
        toBlockId: 'debug.log',
        fromPortId: 'text',
        titleKey: K('basics-chain') + '.steps.connect.title',
        textKey: K('basics-chain') + '.steps.connect.text',
        hintKey: K('basics-chain') + '.steps.connect.hint',
        target: 'canvas',
      },
      {
        id: 'run',
        kind: 'run',
        titleKey: K('basics-chain') + '.steps.run.title',
        textKey: K('basics-chain') + '.steps.run.text',
        hintKey: K('basics-chain') + '.steps.run.hint',
        target: 'run',
      },
      {
        id: 'debug',
        kind: 'open-debug',
        titleKey: K('basics-chain') + '.steps.debug.title',
        textKey: K('basics-chain') + '.steps.debug.text',
        target: 'debug',
      },
    ],
  },

  // ---------- Уровень 3. Логика и данные ----------
  {
    id: 'logic-condition',
    level: 3,
    track: 'basics',
    titleKey: K('logic-condition') + '.title',
    descriptionKey: K('logic-condition') + '.description',
    estimatedMinutes: 9,
    difficulty: 'basic',
    prerequisites: ['basics-chain'],
    sandbox: true,
    relatedBlockIds: ['telegram.message_received', 'logic.condition', 'debug.log'],
    steps: [
      {
        id: 'about',
        kind: 'information',
        titleKey: K('logic-condition') + '.steps.about.title',
        textKey: K('logic-condition') + '.steps.about.text',
      },
      {
        id: 'add-trigger',
        kind: 'add-block',
        blockId: 'telegram.message_received',
        titleKey: K('logic-condition') + '.steps.addTrigger.title',
        textKey: K('logic-condition') + '.steps.addTrigger.text',
      },
      {
        id: 'add-condition',
        kind: 'add-block',
        blockId: 'logic.condition',
        titleKey: K('logic-condition') + '.steps.addCondition.title',
        textKey: K('logic-condition') + '.steps.addCondition.text',
        hintKey: K('logic-condition') + '.steps.addCondition.hint',
      },
      {
        id: 'set-operator',
        kind: 'configure',
        blockId: 'logic.condition',
        configKey: 'operator',
        equals: 'contains',
        titleKey: K('logic-condition') + '.steps.setOperator.title',
        textKey: K('logic-condition') + '.steps.setOperator.text',
        hintKey: K('logic-condition') + '.steps.setOperator.hint',
        target: 'inspector',
      },
      {
        id: 'set-target',
        kind: 'configure',
        blockId: 'logic.condition',
        configKey: 'target',
        notEmpty: true,
        titleKey: K('logic-condition') + '.steps.setTarget.title',
        textKey: K('logic-condition') + '.steps.setTarget.text',
        hintKey: K('logic-condition') + '.steps.setTarget.hint',
        target: 'inspector',
      },
      {
        id: 'connect-in',
        kind: 'connect',
        fromBlockId: 'telegram.message_received',
        toBlockId: 'logic.condition',
        fromPortId: 'text',
        titleKey: K('logic-condition') + '.steps.connectIn.title',
        textKey: K('logic-condition') + '.steps.connectIn.text',
      },
      {
        id: 'add-log',
        kind: 'add-block',
        blockId: 'debug.log',
        titleKey: K('logic-condition') + '.steps.addLog.title',
        textKey: K('logic-condition') + '.steps.addLog.text',
      },
      {
        id: 'connect-true',
        kind: 'connect',
        fromBlockId: 'logic.condition',
        toBlockId: 'debug.log',
        fromPortId: 'true',
        titleKey: K('logic-condition') + '.steps.connectTrue.title',
        textKey: K('logic-condition') + '.steps.connectTrue.text',
        hintKey: K('logic-condition') + '.steps.connectTrue.hint',
      },
      {
        id: 'run',
        kind: 'send-simulator-message',
        source: 'telegram',
        titleKey: K('logic-condition') + '.steps.run.title',
        textKey: K('logic-condition') + '.steps.run.text',
        hintKey: K('logic-condition') + '.steps.run.hint',
        target: 'simulator',
      },
      {
        id: 'quiz-branch',
        kind: 'quiz',
        titleKey: K('logic-condition') + '.steps.quizBranch.title',
        textKey: K('logic-condition') + '.steps.quizBranch.text',
        questionKey: K('logic-condition') + '.steps.quizBranch.question',
        options: [
          { id: 'true', labelKey: K('logic-condition') + '.steps.quizBranch.optTrue', correct: true },
          { id: 'false', labelKey: K('logic-condition') + '.steps.quizBranch.optFalse', correct: false },
          { id: 'both', labelKey: K('logic-condition') + '.steps.quizBranch.optBoth', correct: false },
        ],
      },
    ],
  },
  {
    id: 'data-converters',
    level: 3,
    track: 'basics',
    titleKey: K('data-converters') + '.title',
    descriptionKey: K('data-converters') + '.description',
    estimatedMinutes: 8,
    difficulty: 'basic',
    prerequisites: ['basics-chain'],
    sandbox: true,
    relatedBlockIds: ['core.text', 'data.text_to_number', 'debug.log'],
    steps: [
      {
        id: 'about',
        kind: 'information',
        titleKey: K('data-converters') + '.steps.about.title',
        textKey: K('data-converters') + '.steps.about.text',
        detailsKey: K('data-converters') + '.steps.about.details',
      },
      {
        id: 'add-text',
        kind: 'add-block',
        blockId: 'core.text',
        titleKey: K('data-converters') + '.steps.addText.title',
        textKey: K('data-converters') + '.steps.addText.text',
      },
      {
        id: 'set-value',
        kind: 'configure',
        blockId: 'core.text',
        configKey: 'value',
        equals: '42',
        titleKey: K('data-converters') + '.steps.setValue.title',
        textKey: K('data-converters') + '.steps.setValue.text',
        hintKey: K('data-converters') + '.steps.setValue.hint',
        target: 'inspector',
      },
      {
        id: 'add-converter',
        kind: 'add-block',
        blockId: 'data.text_to_number',
        titleKey: K('data-converters') + '.steps.addConverter.title',
        textKey: K('data-converters') + '.steps.addConverter.text',
        hintKey: K('data-converters') + '.steps.addConverter.hint',
      },
      {
        id: 'connect-1',
        kind: 'connect',
        fromBlockId: 'core.text',
        toBlockId: 'data.text_to_number',
        fromPortId: 'text',
        toPortId: 'value',
        titleKey: K('data-converters') + '.steps.connect1.title',
        textKey: K('data-converters') + '.steps.connect1.text',
      },
      {
        id: 'add-log',
        kind: 'add-block',
        blockId: 'debug.log',
        titleKey: K('data-converters') + '.steps.addLog.title',
        textKey: K('data-converters') + '.steps.addLog.text',
      },
      {
        id: 'connect-2',
        kind: 'connect',
        fromBlockId: 'data.text_to_number',
        toBlockId: 'debug.log',
        fromPortId: 'value',
        toPortId: 'value',
        titleKey: K('data-converters') + '.steps.connect2.title',
        textKey: K('data-converters') + '.steps.connect2.text',
      },
      {
        id: 'run',
        kind: 'run',
        titleKey: K('data-converters') + '.steps.run.title',
        textKey: K('data-converters') + '.steps.run.text',
        target: 'run',
      },
      {
        id: 'debug',
        kind: 'open-debug',
        tab: 'ports',
        titleKey: K('data-converters') + '.steps.debug.title',
        textKey: K('data-converters') + '.steps.debug.text',
        target: 'debug',
      },
    ],
  },

  // ---------- Уровень 4. Первый Telegram-бот ----------
  {
    id: 'telegram-first-bot',
    level: 4,
    track: 'telegram',
    titleKey: K('telegram-first-bot') + '.title',
    descriptionKey: K('telegram-first-bot') + '.description',
    estimatedMinutes: 8,
    difficulty: 'basic',
    prerequisites: ['basics-chain'],
    sandbox: true,
    relatedBlockIds: ['telegram.message_received', 'telegram.send_message'],
    steps: [
      {
        id: 'about',
        kind: 'information',
        titleKey: K('telegram-first-bot') + '.steps.about.title',
        textKey: K('telegram-first-bot') + '.steps.about.text',
        detailsKey: K('telegram-first-bot') + '.steps.about.details',
      },
      {
        id: 'add-trigger',
        kind: 'add-block',
        blockId: 'telegram.message_received',
        titleKey: K('telegram-first-bot') + '.steps.addTrigger.title',
        textKey: K('telegram-first-bot') + '.steps.addTrigger.text',
      },
      {
        id: 'add-send',
        kind: 'add-block',
        blockId: 'telegram.send_message',
        titleKey: K('telegram-first-bot') + '.steps.addSend.title',
        textKey: K('telegram-first-bot') + '.steps.addSend.text',
      },
      {
        id: 'connect-text',
        kind: 'connect',
        fromBlockId: 'telegram.message_received',
        toBlockId: 'telegram.send_message',
        fromPortId: 'text',
        toPortId: 'text',
        titleKey: K('telegram-first-bot') + '.steps.connectText.title',
        textKey: K('telegram-first-bot') + '.steps.connectText.text',
        hintKey: K('telegram-first-bot') + '.steps.connectText.hint',
      },
      {
        id: 'connect-chat',
        kind: 'connect',
        fromBlockId: 'telegram.message_received',
        toBlockId: 'telegram.send_message',
        fromPortId: 'chat_id',
        toPortId: 'chat_id',
        titleKey: K('telegram-first-bot') + '.steps.connectChat.title',
        textKey: K('telegram-first-bot') + '.steps.connectChat.text',
        hintKey: K('telegram-first-bot') + '.steps.connectChat.hint',
      },
      {
        id: 'send',
        kind: 'send-simulator-message',
        source: 'telegram',
        titleKey: K('telegram-first-bot') + '.steps.send.title',
        textKey: K('telegram-first-bot') + '.steps.send.text',
        hintKey: K('telegram-first-bot') + '.steps.send.hint',
        target: 'simulator',
      },
      {
        id: 'chat',
        kind: 'open-debug',
        tab: 'chat',
        titleKey: K('telegram-first-bot') + '.steps.chat.title',
        textKey: K('telegram-first-bot') + '.steps.chat.text',
        target: 'chat',
      },
      {
        id: 'quiz-token',
        kind: 'quiz',
        titleKey: K('telegram-first-bot') + '.steps.quizToken.title',
        textKey: K('telegram-first-bot') + '.steps.quizToken.text',
        questionKey: K('telegram-first-bot') + '.steps.quizToken.question',
        options: [
          { id: 'vault', labelKey: K('telegram-first-bot') + '.steps.quizToken.optVault', correct: true },
          { id: 'project', labelKey: K('telegram-first-bot') + '.steps.quizToken.optProject', correct: false },
          { id: 'browser', labelKey: K('telegram-first-bot') + '.steps.quizToken.optBrowser', correct: false },
        ],
      },
    ],
  },
  {
    id: 'telegram-command',
    level: 4,
    track: 'telegram',
    titleKey: K('telegram-command') + '.title',
    descriptionKey: K('telegram-command') + '.description',
    estimatedMinutes: 8,
    difficulty: 'basic',
    prerequisites: ['telegram-first-bot'],
    sandbox: true,
    relatedBlockIds: ['telegram.command', 'telegram.send_message'],
    steps: [
      {
        id: 'about',
        kind: 'information',
        titleKey: K('telegram-command') + '.steps.about.title',
        textKey: K('telegram-command') + '.steps.about.text',
      },
      {
        id: 'add-command',
        kind: 'add-block',
        blockId: 'telegram.command',
        titleKey: K('telegram-command') + '.steps.addCommand.title',
        textKey: K('telegram-command') + '.steps.addCommand.text',
      },
      {
        id: 'set-command',
        kind: 'configure',
        blockId: 'telegram.command',
        configKey: 'command',
        equals: '/start',
        titleKey: K('telegram-command') + '.steps.setCommand.title',
        textKey: K('telegram-command') + '.steps.setCommand.text',
        hintKey: K('telegram-command') + '.steps.setCommand.hint',
        target: 'inspector',
      },
      {
        id: 'add-send',
        kind: 'add-block',
        blockId: 'telegram.send_message',
        titleKey: K('telegram-command') + '.steps.addSend.title',
        textKey: K('telegram-command') + '.steps.addSend.text',
      },
      {
        id: 'connect-text',
        kind: 'connect',
        fromBlockId: 'telegram.command',
        toBlockId: 'telegram.send_message',
        fromPortId: 'command',
        toPortId: 'text',
        titleKey: K('telegram-command') + '.steps.connectText.title',
        textKey: K('telegram-command') + '.steps.connectText.text',
      },
      {
        id: 'connect-chat',
        kind: 'connect',
        fromBlockId: 'telegram.command',
        toBlockId: 'telegram.send_message',
        fromPortId: 'chat_id',
        toPortId: 'chat_id',
        titleKey: K('telegram-command') + '.steps.connectChat.title',
        textKey: K('telegram-command') + '.steps.connectChat.text',
      },
      {
        id: 'send',
        kind: 'send-simulator-message',
        source: 'telegram',
        titleKey: K('telegram-command') + '.steps.send.title',
        textKey: K('telegram-command') + '.steps.send.text',
        hintKey: K('telegram-command') + '.steps.send.hint',
        target: 'simulator',
      },
      {
        id: 'chat',
        kind: 'open-debug',
        titleKey: K('telegram-command') + '.steps.chat.title',
        textKey: K('telegram-command') + '.steps.chat.text',
        target: 'chat',
      },
    ],
  },

  // ---------- Уровень 5. Web-интерфейс ----------
  {
    id: 'web-first-page',
    level: 5,
    track: 'web',
    titleKey: K('web-first-page') + '.title',
    descriptionKey: K('web-first-page') + '.description',
    estimatedMinutes: 7,
    difficulty: 'basic',
    prerequisites: ['basics-chain'],
    sandbox: true,
    relatedBlockIds: ['web.page', 'web.button', 'debug.log'],
    plannedNoteKey: K('web-first-page') + '.plannedNote',
    steps: [
      {
        id: 'about',
        kind: 'information',
        titleKey: K('web-first-page') + '.steps.about.title',
        textKey: K('web-first-page') + '.steps.about.text',
        detailsKey: K('web-first-page') + '.steps.about.details',
      },
      {
        id: 'add-page',
        kind: 'add-block',
        blockId: 'web.page',
        titleKey: K('web-first-page') + '.steps.addPage.title',
        textKey: K('web-first-page') + '.steps.addPage.text',
      },
      {
        id: 'add-button',
        kind: 'add-block',
        blockId: 'web.button',
        titleKey: K('web-first-page') + '.steps.addButton.title',
        textKey: K('web-first-page') + '.steps.addButton.text',
      },
      {
        id: 'add-log',
        kind: 'add-block',
        blockId: 'debug.log',
        titleKey: K('web-first-page') + '.steps.addLog.title',
        textKey: K('web-first-page') + '.steps.addLog.text',
      },
      {
        id: 'connect',
        kind: 'connect',
        fromBlockId: 'web.button',
        toBlockId: 'debug.log',
        titleKey: K('web-first-page') + '.steps.connect.title',
        textKey: K('web-first-page') + '.steps.connect.text',
      },
      {
        id: 'run-web',
        kind: 'send-simulator-message',
        source: 'web',
        titleKey: K('web-first-page') + '.steps.runWeb.title',
        textKey: K('web-first-page') + '.steps.runWeb.text',
        hintKey: K('web-first-page') + '.steps.runWeb.hint',
        target: 'simulator',
      },
      {
        id: 'debug',
        kind: 'open-debug',
        titleKey: K('web-first-page') + '.steps.debug.title',
        textKey: K('web-first-page') + '.steps.debug.text',
        target: 'debug',
      },
    ],
  },

  // ---------- Уровень 6. Модели ----------
  {
    id: 'models-first-model',
    level: 6,
    track: 'models',
    titleKey: K('models-first-model') + '.title',
    descriptionKey: K('models-first-model') + '.description',
    estimatedMinutes: 9,
    difficulty: 'advanced',
    prerequisites: ['data-converters'],
    sandbox: true,
    relatedBlockIds: ['core.text', 'debug.log', 'models.call'],
    steps: [
      {
        id: 'about',
        kind: 'information',
        titleKey: K('models-first-model') + '.steps.about.title',
        textKey: K('models-first-model') + '.steps.about.text',
        detailsKey: K('models-first-model') + '.steps.about.details',
      },
      {
        id: 'add-text',
        kind: 'add-block',
        blockId: 'core.text',
        titleKey: K('models-first-model') + '.steps.addText.title',
        textKey: K('models-first-model') + '.steps.addText.text',
      },
      {
        id: 'add-log',
        kind: 'add-block',
        blockId: 'debug.log',
        titleKey: K('models-first-model') + '.steps.addLog.title',
        textKey: K('models-first-model') + '.steps.addLog.text',
      },
      {
        id: 'connect',
        kind: 'connect',
        fromBlockId: 'core.text',
        toBlockId: 'debug.log',
        titleKey: K('models-first-model') + '.steps.connect.title',
        textKey: K('models-first-model') + '.steps.connect.text',
      },
      {
        id: 'create-model',
        kind: 'create-model',
        titleKey: K('models-first-model') + '.steps.createModel.title',
        textKey: K('models-first-model') + '.steps.createModel.text',
        hintKey: K('models-first-model') + '.steps.createModel.hint',
        target: 'canvas',
      },
      {
        id: 'run',
        kind: 'run',
        titleKey: K('models-first-model') + '.steps.run.title',
        textKey: K('models-first-model') + '.steps.run.text',
        target: 'run',
      },
      {
        id: 'drilldown',
        kind: 'information',
        titleKey: K('models-first-model') + '.steps.drilldown.title',
        textKey: K('models-first-model') + '.steps.drilldown.text',
      },
      {
        id: 'quiz-value',
        kind: 'quiz',
        titleKey: K('models-first-model') + '.steps.quizValue.title',
        textKey: K('models-first-model') + '.steps.quizValue.text',
        questionKey: K('models-first-model') + '.steps.quizValue.question',
        options: [
          { id: 'reuse', labelKey: K('models-first-model') + '.steps.quizValue.optReuse', correct: true },
          { id: 'beauty', labelKey: K('models-first-model') + '.steps.quizValue.optBeauty', correct: false },
          { id: 'speed', labelKey: K('models-first-model') + '.steps.quizValue.optSpeed', correct: false },
        ],
      },
    ],
  },

  // ---------- Уровень 7. Отладка ----------
  {
    id: 'debug-why-not-working',
    level: 7,
    track: 'debug',
    titleKey: K('debug-why-not-working') + '.title',
    descriptionKey: K('debug-why-not-working') + '.description',
    estimatedMinutes: 8,
    difficulty: 'basic',
    prerequisites: ['basics-chain'],
    sandbox: true,
    relatedBlockIds: ['debug.log', 'core.text'],
    steps: [
      {
        id: 'about',
        kind: 'information',
        titleKey: K('debug-why-not-working') + '.steps.about.title',
        textKey: K('debug-why-not-working') + '.steps.about.text',
      },
      {
        id: 'add-text',
        kind: 'add-block',
        blockId: 'core.text',
        titleKey: K('debug-why-not-working') + '.steps.addText.title',
        textKey: K('debug-why-not-working') + '.steps.addText.text',
      },
      {
        id: 'add-log',
        kind: 'add-block',
        blockId: 'debug.log',
        titleKey: K('debug-why-not-working') + '.steps.addLog.title',
        textKey: K('debug-why-not-working') + '.steps.addLog.text',
      },
      {
        id: 'connect',
        kind: 'connect',
        fromBlockId: 'core.text',
        toBlockId: 'debug.log',
        titleKey: K('debug-why-not-working') + '.steps.connect.title',
        textKey: K('debug-why-not-working') + '.steps.connect.text',
      },
      {
        id: 'run',
        kind: 'run',
        titleKey: K('debug-why-not-working') + '.steps.run.title',
        textKey: K('debug-why-not-working') + '.steps.run.text',
        target: 'run',
      },
      {
        id: 'open-debug',
        kind: 'open-debug',
        titleKey: K('debug-why-not-working') + '.steps.openDebug.title',
        textKey: K('debug-why-not-working') + '.steps.openDebug.text',
        target: 'debug',
      },
      {
        id: 'ports-tab',
        kind: 'information',
        titleKey: K('debug-why-not-working') + '.steps.portsTab.title',
        textKey: K('debug-why-not-working') + '.steps.portsTab.text',
        detailsKey: K('debug-why-not-working') + '.steps.portsTab.details',
        target: 'debug',
      },
      {
        id: 'history-tab',
        kind: 'information',
        titleKey: K('debug-why-not-working') + '.steps.historyTab.title',
        textKey: K('debug-why-not-working') + '.steps.historyTab.text',
        target: 'history',
      },
      {
        id: 'quiz-where',
        kind: 'quiz',
        titleKey: K('debug-why-not-working') + '.steps.quizWhere.title',
        textKey: K('debug-why-not-working') + '.steps.quizWhere.text',
        questionKey: K('debug-why-not-working') + '.steps.quizWhere.question',
        options: [
          { id: 'ports', labelKey: K('debug-why-not-working') + '.steps.quizWhere.optPorts', correct: true },
          { id: 'chat', labelKey: K('debug-why-not-working') + '.steps.quizWhere.optChat', correct: false },
          { id: 'inspector', labelKey: K('debug-why-not-working') + '.steps.quizWhere.optInspector', correct: false },
        ],
      },
    ],
  },

  // ---------- Уровень 8. Черновик, LIVE и публикация ----------
  // Переключатель режимов на холсте визуальный; серверная публикация
  // через API уже реализована. Урок не требует действий с рабочим проектом.
  {
    id: 'publish-versions',
    level: 8,
    track: 'publish',
    titleKey: K('publish-versions') + '.title',
    descriptionKey: K('publish-versions') + '.description',
    estimatedMinutes: 5,
    difficulty: 'basic',
    prerequisites: ['debug-why-not-working'],
    sandbox: false,
    plannedNoteKey: K('publish-versions') + '.plannedNote',
    steps: [
      {
        id: 'about',
        kind: 'information',
        titleKey: K('publish-versions') + '.steps.about.title',
        textKey: K('publish-versions') + '.steps.about.text',
      },
      {
        id: 'modes',
        kind: 'information',
        titleKey: K('publish-versions') + '.steps.modes.title',
        textKey: K('publish-versions') + '.steps.modes.text',
        detailsKey: K('publish-versions') + '.steps.modes.details',
      },
      {
        id: 'preview',
        kind: 'publish-preview',
        titleKey: K('publish-versions') + '.steps.preview.title',
        textKey: K('publish-versions') + '.steps.preview.text',
      },
      {
        id: 'quiz-live',
        kind: 'quiz',
        titleKey: K('publish-versions') + '.steps.quizLive.title',
        textKey: K('publish-versions') + '.steps.quizLive.text',
        questionKey: K('publish-versions') + '.steps.quizLive.question',
        options: [
          { id: 'frozen', labelKey: K('publish-versions') + '.steps.quizLive.optFrozen', correct: true },
          { id: 'draft', labelKey: K('publish-versions') + '.steps.quizLive.optDraft', correct: false },
          { id: 'always', labelKey: K('publish-versions') + '.steps.quizLive.optAlways', correct: false },
        ],
      },
    ],
  },
];
