/**
 * Расширенные детали Telegram (Этап 4, часть B).
 *
 * Определения фиксируют контракты портов и место в библиотеке
 * (статус `planned`, скрыты из палитры). Исполнение появится вместе с
 * реальным транспортом бота (см. docs/TELEGRAM.md) — до тех пор детали
 * не выдаются за реализованные.
 */

import type { BlockDefinition } from '@/core/types/blocks';
import { dport, eport } from '../shared';

export const telegramExtendedBlocks: BlockDefinition[] = [
  // ─────────────────────────── События ───────────────────────────
  {
    id: 'telegram.callback_query',
    version: '1',
    labelKey: 'blocks.telegram.callback_query.label',
    descriptionKey: 'blocks.telegram.callback_query.description',
    keywords: ['телеграм', 'кнопка', 'инлайн', 'нажатие', 'колбэк', 'триггер'],
    category: 'telegram_events',
    subcategory: 'inline',
    difficulty: 'basic',
    status: 'planned',
    available: false,
    trigger: true,
    inputs: [],
    outputs: [
      dport('data', 'blocks.ports.data', 'text'),
      dport('message_id', 'blocks.ports.message_id', 'number'),
      dport('user_id', 'blocks.ports.user_id', 'number'),
      dport('chat_id', 'blocks.ports.chat_id', 'number'),
    ],
    ui: { icon: '🔘', color: '#60a5fa' },
  },
  {
    id: 'telegram.edited_message',
    version: '1',
    labelKey: 'blocks.telegram.edited_message.label',
    descriptionKey: 'blocks.telegram.edited_message.description',
    keywords: ['телеграм', 'правка', 'изменение', 'сообщение', 'триггер'],
    category: 'telegram_events',
    subcategory: 'сообщения',
    difficulty: 'advanced',
    status: 'planned',
    available: false,
    trigger: true,
    inputs: [],
    outputs: [
      dport('text', 'blocks.ports.text', 'text'),
      dport('message_id', 'blocks.ports.message_id', 'number'),
      dport('user_id', 'blocks.ports.user_id', 'number'),
      dport('chat_id', 'blocks.ports.chat_id', 'number'),
    ],
    ui: { icon: '✏️', color: '#60a5fa' },
  },
  {
    id: 'telegram.photo_received',
    version: '1',
    labelKey: 'blocks.telegram.photo_received.label',
    descriptionKey: 'blocks.telegram.photo_received.description',
    keywords: ['телеграм', 'фото', 'картинка', 'входящее', 'файл', 'триггер'],
    category: 'telegram_events',
    subcategory: 'вложения',
    difficulty: 'basic',
    status: 'planned',
    available: false,
    trigger: true,
    inputs: [],
    outputs: [
      dport('photo', 'blocks.ports.photo', 'image'),
      dport('file_id', 'blocks.ports.file_id', 'text'),
      dport('caption', 'blocks.ports.caption', 'text'),
      dport('user_id', 'blocks.ports.user_id', 'number'),
      dport('chat_id', 'blocks.ports.chat_id', 'number'),
    ],
    ui: { icon: '📷', color: '#60a5fa' },
  },
  {
    id: 'telegram.voice_received',
    version: '1',
    labelKey: 'blocks.telegram.voice_received.label',
    descriptionKey: 'blocks.telegram.voice_received.description',
    keywords: ['телеграм', 'голос', 'аудио', 'сообщение', 'файл', 'триггер'],
    category: 'telegram_events',
    subcategory: 'вложения',
    difficulty: 'advanced',
    status: 'planned',
    available: false,
    trigger: true,
    inputs: [],
    outputs: [
      dport('file_id', 'blocks.ports.file_id', 'text'),
      dport('duration', 'blocks.ports.duration', 'number'),
      dport('user_id', 'blocks.ports.user_id', 'number'),
      dport('chat_id', 'blocks.ports.chat_id', 'number'),
    ],
    ui: { icon: '🎙️', color: '#60a5fa' },
  },
  {
    id: 'telegram.document_received',
    version: '1',
    labelKey: 'blocks.telegram.document_received.label',
    descriptionKey: 'blocks.telegram.document_received.description',
    keywords: ['телеграм', 'документ', 'файл', 'вложение', 'триггер'],
    category: 'telegram_events',
    subcategory: 'вложения',
    difficulty: 'basic',
    status: 'planned',
    available: false,
    trigger: true,
    inputs: [],
    outputs: [
      dport('file', 'blocks.ports.file', 'file'),
      dport('file_id', 'blocks.ports.file_id', 'text'),
      dport('filename', 'blocks.ports.filename', 'text'),
      dport('user_id', 'blocks.ports.user_id', 'number'),
      dport('chat_id', 'blocks.ports.chat_id', 'number'),
    ],
    ui: { icon: '📄', color: '#60a5fa' },
  },
  {
    id: 'telegram.location_received',
    version: '1',
    labelKey: 'blocks.telegram.location_received.label',
    descriptionKey: 'blocks.telegram.location_received.description',
    keywords: ['телеграм', 'локация', 'гео', 'координаты', 'место', 'триггер'],
    category: 'telegram_events',
    subcategory: 'вложения',
    difficulty: 'advanced',
    status: 'planned',
    available: false,
    trigger: true,
    inputs: [],
    outputs: [
      dport('latitude', 'blocks.ports.latitude', 'number'),
      dport('longitude', 'blocks.ports.longitude', 'number'),
      dport('user_id', 'blocks.ports.user_id', 'number'),
      dport('chat_id', 'blocks.ports.chat_id', 'number'),
    ],
    ui: { icon: '📍', color: '#60a5fa' },
  },
  {
    id: 'telegram.contact_received',
    version: '1',
    labelKey: 'blocks.telegram.contact_received.label',
    descriptionKey: 'blocks.telegram.contact_received.description',
    keywords: ['телеграм', 'контакт', 'телефон', 'визитка', 'триггер'],
    category: 'telegram_events',
    subcategory: 'вложения',
    difficulty: 'advanced',
    status: 'planned',
    available: false,
    trigger: true,
    inputs: [],
    outputs: [
      dport('phone_number', 'blocks.ports.phone_number', 'text'),
      dport('first_name', 'blocks.ports.first_name', 'text'),
      dport('last_name', 'blocks.ports.last_name', 'text'),
      dport('user_id', 'blocks.ports.user_id', 'number'),
      dport('chat_id', 'blocks.ports.chat_id', 'number'),
    ],
    ui: { icon: '👤', color: '#60a5fa' },
  },
  {
    id: 'telegram.inline_query',
    version: '1',
    labelKey: 'blocks.telegram.inline_query.label',
    descriptionKey: 'blocks.telegram.inline_query.description',
    keywords: ['телеграм', 'инлайн', 'поиск', 'запрос', 'триггер'],
    category: 'telegram_events',
    subcategory: 'inline',
    difficulty: 'advanced',
    status: 'planned',
    available: false,
    trigger: true,
    inputs: [],
    outputs: [
      dport('query', 'blocks.ports.query', 'text'),
      dport('user_id', 'blocks.ports.user_id', 'number'),
    ],
    ui: { icon: '🔎', color: '#60a5fa' },
  },
  // ─────────────────────────── Действия ───────────────────────────
  {
    id: 'telegram.send_document',
    version: '1',
    labelKey: 'blocks.telegram.send_document.label',
    descriptionKey: 'blocks.telegram.send_document.description',
    keywords: ['телеграм', 'документ', 'файл', 'отправить'],
    category: 'telegram_actions',
    subcategory: 'отправка',
    difficulty: 'basic',
    status: 'planned',
    available: false,
    inputs: [
      dport('file', 'blocks.ports.file', 'file'),
      dport('caption', 'blocks.ports.caption', 'text'),
      dport('chat_id', 'blocks.ports.chat_id', 'number'),
    ],
    outputs: [dport('message_id', 'blocks.ports.message_id', 'number'), eport()],
    ui: { icon: '📤', color: '#3b82f6' },
  },
  {
    id: 'telegram.edit_message',
    version: '1',
    labelKey: 'blocks.telegram.edit_message.label',
    descriptionKey: 'blocks.telegram.edit_message.description',
    keywords: ['телеграм', 'правка', 'изменить', 'сообщение', 'обновить'],
    category: 'telegram_actions',
    subcategory: 'сообщения',
    difficulty: 'basic',
    status: 'planned',
    available: false,
    inputs: [
      dport('text', 'blocks.ports.text', 'text'),
      dport('message_id', 'blocks.ports.message_id', 'number'),
      dport('chat_id', 'blocks.ports.chat_id', 'number'),
    ],
    outputs: [dport('ok', 'blocks.ports.ok', 'boolean'), eport()],
    ui: { icon: '✍️', color: '#3b82f6' },
  },
  {
    id: 'telegram.delete_message',
    version: '1',
    labelKey: 'blocks.telegram.delete_message.label',
    descriptionKey: 'blocks.telegram.delete_message.description',
    keywords: ['телеграм', 'удалить', 'сообщение'],
    category: 'telegram_actions',
    subcategory: 'сообщения',
    difficulty: 'basic',
    status: 'planned',
    available: false,
    inputs: [
      dport('message_id', 'blocks.ports.message_id', 'number'),
      dport('chat_id', 'blocks.ports.chat_id', 'number'),
    ],
    outputs: [dport('ok', 'blocks.ports.ok', 'boolean'), eport()],
    ui: { icon: '🗑️', color: '#3b82f6' },
  },
  {
    id: 'telegram.answer_callback',
    version: '1',
    labelKey: 'blocks.telegram.answer_callback.label',
    descriptionKey: 'blocks.telegram.answer_callback.description',
    keywords: ['телеграм', 'колбэк', 'ответ', 'кнопка', 'уведомление'],
    category: 'telegram_actions',
    subcategory: 'inline',
    difficulty: 'advanced',
    status: 'planned',
    available: false,
    inputs: [
      dport('text', 'blocks.ports.text', 'text'),
      dport('show_alert', 'blocks.ports.show_alert', 'boolean'),
    ],
    outputs: [dport('ok', 'blocks.ports.ok', 'boolean'), eport()],
    ui: { icon: '✅', color: '#3b82f6' },
  },
  {
    id: 'telegram.send_location',
    version: '1',
    labelKey: 'blocks.telegram.send_location.label',
    descriptionKey: 'blocks.telegram.send_location.description',
    keywords: ['телеграм', 'локация', 'гео', 'координаты', 'отправить'],
    category: 'telegram_actions',
    subcategory: 'отправка',
    difficulty: 'advanced',
    status: 'planned',
    available: false,
    inputs: [
      dport('latitude', 'blocks.ports.latitude', 'number'),
      dport('longitude', 'blocks.ports.longitude', 'number'),
      dport('chat_id', 'blocks.ports.chat_id', 'number'),
    ],
    outputs: [dport('message_id', 'blocks.ports.message_id', 'number'), eport()],
    ui: { icon: '🗺️', color: '#3b82f6' },
  },
  {
    id: 'telegram.send_contact',
    version: '1',
    labelKey: 'blocks.telegram.send_contact.label',
    descriptionKey: 'blocks.telegram.send_contact.description',
    keywords: ['телеграм', 'контакт', 'телефон', 'визитка', 'отправить'],
    category: 'telegram_actions',
    subcategory: 'отправка',
    difficulty: 'advanced',
    status: 'planned',
    available: false,
    inputs: [
      dport('phone_number', 'blocks.ports.phone_number', 'text'),
      dport('first_name', 'blocks.ports.first_name', 'text'),
      dport('chat_id', 'blocks.ports.chat_id', 'number'),
    ],
    outputs: [dport('message_id', 'blocks.ports.message_id', 'number'), eport()],
    ui: { icon: '📇', color: '#3b82f6' },
  },
  {
    id: 'telegram.get_user',
    version: '1',
    labelKey: 'blocks.telegram.get_user.label',
    descriptionKey: 'blocks.telegram.get_user.description',
    keywords: ['телеграм', 'пользователь', 'профиль', 'информация', 'запрос'],
    category: 'telegram_actions',
    subcategory: 'запросы',
    difficulty: 'advanced',
    status: 'planned',
    available: false,
    inputs: [dport('user_id', 'blocks.ports.user_id', 'number')],
    outputs: [dport('user', 'blocks.ports.user', 'user'), eport()],
    ui: { icon: '🪪', color: '#3b82f6' },
  },
  {
    id: 'telegram.get_chat',
    version: '1',
    labelKey: 'blocks.telegram.get_chat.label',
    descriptionKey: 'blocks.telegram.get_chat.description',
    keywords: ['телеграм', 'чат', 'канал', 'группа', 'информация', 'запрос'],
    category: 'telegram_actions',
    subcategory: 'запросы',
    difficulty: 'advanced',
    status: 'planned',
    available: false,
    inputs: [dport('chat_id', 'blocks.ports.chat_id', 'number')],
    outputs: [dport('chat', 'blocks.ports.chat', 'object'), eport()],
    ui: { icon: '💬', color: '#3b82f6' },
  },
];
