/**
 * Категория «HTTP / интернет-запросы» (Этап 4, часть E).
 *
 * Зарезервированный `http.request` (reserved.ts) остаётся общей заготовкой;
 * здесь — конкретные операции. Все определения запланированы
 * (`available: false`): сетевые вызовы появятся вместе с серверным
 * исполнением (см. docs/SECURITY.md §3 и docs/DATABASE.md).
 */

import type { BlockDefinition } from '@/core/types/blocks';
import { dport, eport } from '../shared';

const httpColor = '#fb923c';

export const httpBlocks: BlockDefinition[] = [
  {
    id: 'http.get',
    version: '1',
    labelKey: 'blocks.http.get.label',
    descriptionKey: 'blocks.http.get.description',
    keywords: ['интернет', 'запрос', 'получить', 'скачать', 'апи', 'гет'],
    category: 'http',
    subcategory: 'запросы',
    difficulty: 'basic',
    status: 'planned',
    available: false,
    inputs: [dport('url', 'blocks.ports.url', 'url')],
    outputs: [dport('response', 'blocks.ports.response', 'json'), eport()],
    ui: { icon: '🌍', color: httpColor },
  },
  {
    id: 'http.post',
    version: '1',
    labelKey: 'blocks.http.post.label',
    descriptionKey: 'blocks.http.post.description',
    keywords: ['интернет', 'запрос', 'отправить', 'данные', 'апи', 'пост'],
    category: 'http',
    subcategory: 'запросы',
    difficulty: 'basic',
    status: 'planned',
    available: false,
    inputs: [
      dport('url', 'blocks.ports.url', 'url'),
      dport('body', 'blocks.ports.body', 'json'),
    ],
    outputs: [dport('response', 'blocks.ports.response', 'json'), eport()],
    ui: { icon: '📮', color: httpColor },
  },
  {
    id: 'http.download',
    version: '1',
    labelKey: 'blocks.http.download.label',
    descriptionKey: 'blocks.http.download.description',
    keywords: ['интернет', 'скачать', 'файл', 'загрузка'],
    category: 'http',
    subcategory: 'файлы',
    difficulty: 'advanced',
    status: 'planned',
    available: false,
    inputs: [dport('url', 'blocks.ports.url', 'url')],
    outputs: [dport('file', 'blocks.ports.file', 'file'), eport()],
    ui: { icon: '⬇️', color: httpColor },
  },
  {
    id: 'http.upload',
    version: '1',
    labelKey: 'blocks.http.upload.label',
    descriptionKey: 'blocks.http.upload.description',
    keywords: ['интернет', 'загрузить', 'файл', 'отправить'],
    category: 'http',
    subcategory: 'файлы',
    difficulty: 'advanced',
    status: 'planned',
    available: false,
    inputs: [
      dport('url', 'blocks.ports.url', 'url'),
      dport('file', 'blocks.ports.file', 'file'),
    ],
    outputs: [dport('response', 'blocks.ports.response', 'json'), eport()],
    ui: { icon: '⬆️', color: httpColor },
  },
  {
    id: 'http.webhook',
    version: '1',
    labelKey: 'blocks.http.webhook.label',
    descriptionKey: 'blocks.http.webhook.description',
    keywords: ['интернет', 'вебхук', 'внешний вызов', 'триггер', 'апи'],
    category: 'http',
    subcategory: 'триггеры',
    difficulty: 'advanced',
    status: 'planned',
    available: false,
    trigger: true,
    inputs: [],
    outputs: [dport('body', 'blocks.ports.body', 'json'), dport('headers', 'blocks.ports.headers', 'object')],
    ui: { icon: '🪝', color: httpColor },
  },
  {
    id: 'http.respond',
    version: '1',
    labelKey: 'blocks.http.respond.label',
    descriptionKey: 'blocks.http.respond.description',
    keywords: ['интернет', 'ответ', 'вебхук', 'статус'],
    category: 'http',
    subcategory: 'ответы',
    difficulty: 'advanced',
    status: 'planned',
    available: false,
    inputs: [
      dport('body', 'blocks.ports.body', 'json'),
      dport('status', 'blocks.ports.status', 'number'),
    ],
    outputs: [dport('ok', 'blocks.ports.ok', 'boolean')],
    ui: { icon: '📤', color: httpColor },
  },
  {
    id: 'http.timeout',
    version: '1',
    labelKey: 'blocks.http.timeout.label',
    descriptionKey: 'blocks.http.timeout.description',
    keywords: ['интернет', 'таймаут', 'ожидание', 'лимит времени'],
    category: 'http',
    subcategory: 'настройки',
    difficulty: 'advanced',
    status: 'planned',
    available: false,
    inputs: [dport('value', 'blocks.ports.value', 'any')],
    outputs: [dport('value', 'blocks.ports.value', 'any'), eport()],
    defaults: { ms: 5000 },
    ui: { icon: '⏳', color: httpColor },
  },
  {
    id: 'http.encode_uri',
    version: '1',
    labelKey: 'blocks.http.encode_uri.label',
    descriptionKey: 'blocks.http.encode_uri.description',
    keywords: ['интернет', 'адрес', 'кодировать', 'экранировать', 'ссылка'],
    category: 'http',
    subcategory: 'преобразование',
    difficulty: 'basic',
    status: 'planned',
    available: false,
    inputs: [dport('text', 'blocks.ports.text', 'text')],
    outputs: [dport('url', 'blocks.ports.url', 'url'), eport()],
    ui: { icon: '🔐', color: httpColor },
  },
  {
    id: 'http.build_url',
    version: '1',
    labelKey: 'blocks.http.build_url.label',
    descriptionKey: 'blocks.http.build_url.description',
    keywords: ['интернет', 'адрес', 'собрать', 'параметры', 'запрос'],
    category: 'http',
    subcategory: 'преобразование',
    difficulty: 'basic',
    status: 'planned',
    available: false,
    inputs: [
      dport('base', 'blocks.ports.base', 'url'),
      dport('params', 'blocks.ports.params', 'object'),
    ],
    outputs: [dport('url', 'blocks.ports.url', 'url'), eport()],
    ui: { icon: '🧩', color: httpColor },
  },
];
