/**
 * Детали веб-интерфейса (Этап 4, часть C).
 *
 * Элементы оформления страницы: текст, заголовки, картинки, поля ввода,
 * контейнеры. Определения фиксируют контракты и место в библиотеке
 * (статус `planned`, скрыты из палитры). Рендеринг собранной страницы
 * появится вместе с развитием веб-превью (см. docs/WEB.md).
 */

import type { BlockDefinition } from '@/core/types/blocks';
import { dport } from '../shared';

export const webUiBlocks: BlockDefinition[] = [
  {
    id: 'web.text',
    version: '1',
    labelKey: 'blocks.web.text.label',
    descriptionKey: 'blocks.web.text.description',
    keywords: ['веб', 'текст', 'абзац', 'надпись', 'элемент'],
    category: 'web_ui',
    subcategory: 'оформление',
    difficulty: 'basic',
    status: 'planned',
    available: false,
    inputs: [dport('text', 'blocks.ports.text', 'text')],
    outputs: [dport('element', 'blocks.ports.element', 'object')],
    ui: { icon: '🧱', color: '#f472b6' },
  },
  {
    id: 'web.heading',
    version: '1',
    labelKey: 'blocks.web.heading.label',
    descriptionKey: 'blocks.web.heading.description',
    keywords: ['веб', 'заголовок', 'название', 'раздел'],
    category: 'web_ui',
    subcategory: 'оформление',
    difficulty: 'basic',
    status: 'planned',
    available: false,
    inputs: [
      dport('text', 'blocks.ports.text', 'text'),
      dport('level', 'blocks.ports.level', 'number'),
    ],
    outputs: [dport('element', 'blocks.ports.element', 'object')],
    ui: { icon: '🅷', color: '#f472b6' },
  },
  {
    id: 'web.image',
    version: '1',
    labelKey: 'blocks.web.image.label',
    descriptionKey: 'blocks.web.image.description',
    keywords: ['веб', 'картинка', 'изображение', 'лого'],
    category: 'web_ui',
    subcategory: 'оформление',
    difficulty: 'basic',
    status: 'planned',
    available: false,
    inputs: [
      dport('src', 'blocks.ports.src', 'url'),
      dport('caption', 'blocks.ports.caption', 'text'),
    ],
    outputs: [dport('element', 'blocks.ports.element', 'object')],
    ui: { icon: '🖼️', color: '#f472b6' },
  },
  {
    id: 'web.input',
    version: '1',
    labelKey: 'blocks.web.input.label',
    descriptionKey: 'blocks.web.input.description',
    keywords: ['веб', 'поле', 'ввод', 'строка', 'форма'],
    category: 'web_ui',
    subcategory: 'ввод',
    difficulty: 'basic',
    status: 'planned',
    available: false,
    inputs: [
      dport('label', 'blocks.ports.label', 'text'),
      dport('placeholder', 'blocks.ports.placeholder', 'text'),
    ],
    outputs: [dport('element', 'blocks.ports.element', 'object')],
    ui: { icon: '⌨️', color: '#f472b6' },
  },
  {
    id: 'web.textarea',
    version: '1',
    labelKey: 'blocks.web.textarea.label',
    descriptionKey: 'blocks.web.textarea.description',
    keywords: ['веб', 'текстовое поле', 'многострочный', 'ввод', 'комментарий'],
    category: 'web_ui',
    subcategory: 'ввод',
    difficulty: 'basic',
    status: 'planned',
    available: false,
    inputs: [
      dport('label', 'blocks.ports.label', 'text'),
      dport('placeholder', 'blocks.ports.placeholder', 'text'),
    ],
    outputs: [dport('element', 'blocks.ports.element', 'object')],
    ui: { icon: '📝', color: '#f472b6' },
  },
  {
    id: 'web.link',
    version: '1',
    labelKey: 'blocks.web.link.label',
    descriptionKey: 'blocks.web.link.description',
    keywords: ['веб', 'ссылка', 'переход', 'адрес'],
    category: 'web_ui',
    subcategory: 'навигация',
    difficulty: 'basic',
    status: 'planned',
    available: false,
    inputs: [
      dport('text', 'blocks.ports.text', 'text'),
      dport('href', 'blocks.ports.href', 'url'),
    ],
    outputs: [dport('element', 'blocks.ports.element', 'object')],
    ui: { icon: '🔗', color: '#f472b6' },
  },
  {
    id: 'web.container',
    version: '1',
    labelKey: 'blocks.web.container.label',
    descriptionKey: 'blocks.web.container.description',
    keywords: ['веб', 'контейнер', 'блок', 'группа элементов'],
    category: 'web_ui',
    subcategory: 'структура',
    difficulty: 'advanced',
    status: 'planned',
    available: false,
    inputs: [dport('children', 'blocks.ports.children', 'array')],
    outputs: [dport('element', 'blocks.ports.element', 'object')],
    ui: { icon: '📦', color: '#f472b6' },
  },
  {
    id: 'web.section',
    version: '1',
    labelKey: 'blocks.web.section.label',
    descriptionKey: 'blocks.web.section.description',
    keywords: ['веб', 'секция', 'раздел', 'блок'],
    category: 'web_ui',
    subcategory: 'структура',
    difficulty: 'advanced',
    status: 'planned',
    available: false,
    inputs: [
      dport('title', 'blocks.ports.title', 'text'),
      dport('children', 'blocks.ports.children', 'array'),
    ],
    outputs: [dport('element', 'blocks.ports.element', 'object')],
    ui: { icon: '🗂️', color: '#f472b6' },
  },
  {
    id: 'web.grid',
    version: '1',
    labelKey: 'blocks.web.grid.label',
    descriptionKey: 'blocks.web.grid.description',
    keywords: ['веб', 'сетка', 'колонки', 'раскладка'],
    category: 'web_ui',
    subcategory: 'структура',
    difficulty: 'advanced',
    status: 'planned',
    available: false,
    inputs: [
      dport('columns', 'blocks.ports.columns', 'number'),
      dport('children', 'blocks.ports.children', 'array'),
    ],
    outputs: [dport('element', 'blocks.ports.element', 'object')],
    ui: { icon: '🧮', color: '#f472b6' },
  },
  {
    id: 'web.modal',
    version: '1',
    labelKey: 'blocks.web.modal.label',
    descriptionKey: 'blocks.web.modal.description',
    keywords: ['веб', 'окно', 'модальное', 'диалог', 'попап'],
    category: 'web_ui',
    subcategory: 'структура',
    difficulty: 'advanced',
    status: 'planned',
    available: false,
    inputs: [
      dport('title', 'blocks.ports.title', 'text'),
      dport('children', 'blocks.ports.children', 'array'),
    ],
    outputs: [dport('element', 'blocks.ports.element', 'object')],
    ui: { icon: '🪟', color: '#f472b6' },
  },
];
