/**
 * Категория «Поток» — управление прохождением данных (Этап 4, часть A).
 *
 * Реализованы простые чистые механики (заслонка, разветвление, слияние).
 * Механики с состоянием/временем (повтор, антидребезг, очередь, интервал)
 * зафиксированы определениями и исполняются по мере развития рантайма.
 */

import type { BlockDefinition } from '@/core/types/blocks';
import { dport } from '../shared';

export const flowControlBlocks: BlockDefinition[] = [
  {
    id: 'flow.gate',
    labelKey: 'blocks.flow.gate.label',
    descriptionKey: 'blocks.flow.gate.description',
    keywords: ['заслонка', 'пропуск', 'включить', 'выключить'],
    category: 'flow',
    subcategory: 'Управление',
    inputs: [dport('value', 'blocks.ports.value', 'any')],
    outputs: [dport('value', 'blocks.ports.value', 'any')],
    defaults: { open: true },
    status: 'implemented',
    difficulty: 'basic',
    runtime: ({ inputs, config }) =>
      config.open === true || config.open === undefined
        ? { outputs: { value: inputs.value } }
        : { outputs: {} },
    ui: { icon: '⊢', color: '#fbbf24' },
  },
  {
    id: 'flow.split',
    labelKey: 'blocks.flow.split.label',
    descriptionKey: 'blocks.flow.split.description',
    keywords: ['разветвление', 'копия', 'параллельно', 'две ветки'],
    category: 'flow',
    subcategory: 'Управление',
    inputs: [dport('value', 'blocks.ports.value', 'any')],
    outputs: [
      dport('a', 'blocks.ports.branch_a', 'any'),
      dport('b', 'blocks.ports.branch_b', 'any'),
    ],
    status: 'implemented',
    difficulty: 'basic',
    runtime: ({ inputs }) => ({ outputs: { a: inputs.value, b: inputs.value } }),
    ui: { icon: '⑂⑂', color: '#fbbf24' },
  },
  {
    id: 'flow.merge',
    labelKey: 'blocks.flow.merge.label',
    descriptionKey: 'blocks.flow.merge.description',
    keywords: ['слияние', 'объединить ветки', 'первое значение'],
    category: 'flow',
    subcategory: 'Управление',
    inputs: [
      dport('a', 'blocks.ports.branch_a', 'any'),
      dport('b', 'blocks.ports.branch_b', 'any'),
    ],
    outputs: [dport('value', 'blocks.ports.value', 'any')],
    status: 'implemented',
    difficulty: 'advanced',
    runtime: ({ inputs }) => ({
      outputs: { value: inputs.a !== undefined ? inputs.a : inputs.b },
    }),
    ui: { icon: '⥂', color: '#fbbf24' },
  },
  {
    id: 'flow.stop',
    labelKey: 'blocks.flow.stop.label',
    descriptionKey: 'blocks.flow.stop.description',
    keywords: ['остановить', 'стоп', 'прервать', 'завершить'],
    category: 'flow',
    subcategory: 'Управление',
    available: false,
    status: 'planned',
    inputs: [dport('value', 'blocks.ports.value', 'any')],
    outputs: [],
    difficulty: 'advanced',
    ui: { icon: '⏹', color: '#fbbf24' },
  },
  {
    id: 'flow.retry',
    labelKey: 'blocks.flow.retry.label',
    descriptionKey: 'blocks.flow.retry.description',
    keywords: ['повтор', 'попытка', 'ещё раз', 'ошибка'],
    category: 'flow',
    subcategory: 'Надёжность',
    available: false,
    status: 'planned',
    inputs: [dport('value', 'blocks.ports.value', 'any')],
    outputs: [dport('value', 'blocks.ports.value', 'any'), dport('error', 'blocks.ports.error', 'error')],
    defaults: { attempts: 3, delayMs: 1000 },
    difficulty: 'advanced',
    ui: { icon: '↻', color: '#fbbf24' },
  },
  {
    id: 'flow.debounce',
    labelKey: 'blocks.flow.debounce.label',
    descriptionKey: 'blocks.flow.debounce.description',
    keywords: ['антидребезг', 'задержка', 'серия', 'последнее'],
    category: 'flow',
    subcategory: 'Время',
    available: false,
    status: 'planned',
    inputs: [dport('value', 'blocks.ports.value', 'any')],
    outputs: [dport('value', 'blocks.ports.value', 'any')],
    defaults: { windowMs: 500 },
    difficulty: 'advanced',
    ui: { icon: '〜', color: '#fbbf24' },
  },
  {
    id: 'flow.throttle',
    labelKey: 'blocks.flow.throttle.label',
    descriptionKey: 'blocks.flow.throttle.description',
    keywords: ['троттлинг', 'ограничение частоты', 'не чаще'],
    category: 'flow',
    subcategory: 'Время',
    available: false,
    status: 'planned',
    inputs: [dport('value', 'blocks.ports.value', 'any')],
    outputs: [dport('value', 'blocks.ports.value', 'any')],
    defaults: { intervalMs: 1000 },
    difficulty: 'advanced',
    ui: { icon: '⏳', color: '#fbbf24' },
  },
  {
    id: 'flow.queue',
    labelKey: 'blocks.flow.queue.label',
    descriptionKey: 'blocks.flow.queue.description',
    keywords: ['очередь', 'по одному', 'последовательно'],
    category: 'flow',
    subcategory: 'Надёжность',
    available: false,
    status: 'planned',
    inputs: [dport('value', 'blocks.ports.value', 'any')],
    outputs: [dport('value', 'blocks.ports.value', 'any')],
    defaults: { concurrency: 1 },
    difficulty: 'advanced',
    ui: { icon: '≡', color: '#fbbf24' },
  },
  {
    id: 'flow.interval',
    labelKey: 'blocks.flow.interval.label',
    descriptionKey: 'blocks.flow.interval.description',
    keywords: ['интервал', 'периодически', 'расписание', 'каждые'],
    category: 'flow',
    subcategory: 'Время',
    trigger: true,
    available: false,
    status: 'planned',
    inputs: [],
    outputs: [dport('tick', 'blocks.ports.tick', 'number')],
    defaults: { intervalMs: 60000 },
    difficulty: 'advanced',
    ui: { icon: '🔁', color: '#fbbf24' },
  },
];
